#snap survey MASTER data
#load required packages
library(tidyverse)
library(lubridate)
library(readxl)
library(DBI)
library(odbc)


# Establish ODBC connections -----------------------------------------------

#ESTABLISH ODBC CONNECTION WITH DATA
Y006 <- odbc::dbConnect(odbc::odbc(),
                           .connection_string = "driver={SQL Server};server=SQLClusColLK19\\Lake19;
                             database=Y006_BBV_PID;
                             Encrypt=true;trusted_connection=true",
                           timeout = 60,
                           timezone = Sys.timezone(),
                           timezone_out = Sys.timezone())



ECDS <- odbc::dbConnect(odbc::odbc(),
                        .connection_string = "driver={SQL Server};server=SQLClusColLK19\\Lake19;
                             database=ECDS;
                             Encrypt=true;trusted_connection=true",
                        timeout = 60,
                        timezone = Sys.timezone(),
                        timezone_out = Sys.timezone())



Sentinel <- odbc::dbConnect(odbc::odbc(),
                        .connection_string = "driver={SQL Server};server=SQLClusColHFN17\\HFN17;
                             database=NIS_HepatitisSentinel;
                             Encrypt=true;trusted_connection=true",
                        timeout = 60,
                        timezone = Sys.timezone(),
                        timezone_out = Sys.timezone())


# Run queries to get data tables ------------------------------------------

#Main ECDS query
ECDS_2223_main <- DBI::dbGetQuery(conn = ECDS, statement =
  "SELECT 
 [vtECDS].PheKey
  ,TOKEN_PERSON_ID
  ,[PROVIDER_CODE_DERIVED]
  ,[SITE]
  ,[ARRIVAL_MONTH]
  ,[ARRIVAL_DATE]
  ,[ECDS].[dbo].[vtECDS].[FYEAR]
  ,[InvestigationIdx]
  ,[INVESTIGATION_DATE]
  ,[INVESTIGATION_CODE]
  ,[CHIEF_COMPLAINT]
  ,[CHIEF_COMPLAINT_Description]
  ,[INVESTIGATION_CODE_Description]

  , CASE 			
  WHEN [PROVIDER_CODE_DERIVED] in ('RRV','RP4','RAL','RAN','RAP','RRP','RP6','RKE','RNK') THEN 'NCL'		
  WHEN [PROVIDER_CODE_DERIVED] in ('R1H','RF4','RWK','RQX','RAT')   THEN 'NEL'		
  WHEN [PROVIDER_CODE_DERIVED] in ('RYJ','RT3','RQM','RKL','R1K','RV3','RAS','RYX') THEN 'NWL'		
  WHEN [PROVIDER_CODE_DERIVED] in ('RJ1','RJZ','RV5','RJ2','RPG')   THEN 'SEL'		
  WHEN [PROVIDER_CODE_DERIVED] in ('RJ7','RVR','RQY','RJ6','RAX','RPY')   THEN 'SWL'	
  WHEN [PROVIDER_CODE_DERIVED] in ('RJ7','RVR','RQY','RJ6','RAX','RPY')   THEN 'SE'	
  ELSE 'Other'  		
  END AS London_Provider_ICS
  
  , CASE 
  WHEN [PROVIDER_CODE_DERIVED] in ('RTP') THEN 'UNIVERSITY HOSPITALS SUSSEX NHS FOUNDATION TRUST' 
  WHEN [PROVIDER_CODE_DERIVED] in ('R0A') THEN 'MANCHESTER UNIVERSITY NHS FOUNDATION TRUST' 
  WHEN [PROVIDER_CODE_DERIVED] in ('RM3') THEN 'SALFORD ROYAL NHS FOUNDATION TRUST' 
  WHEN [PROVIDER_CODE_DERIVED] in ('RXL') THEN 'BLACKPOOL TEACHING HOSPITALS NHS FOUNDATION TRUST' 
  WHEN [PROVIDER_CODE_DERIVED] in ('RRV') THEN 'UNIVERSITY COLLEGE LONDON HOSPITALS NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RP4') THEN 'GREAT ORMOND STREET HOSPITAL FOR CHILDREN NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RAL') THEN 'ROYAL FREE LONDON NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RP6') THEN 'MOORFIELDS EYE HOSPITAL NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RAN') THEN 'ROYAL NATIONAL ORTHOPAEDIC HOSPITAL NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RAP') THEN 'NORTH MIDDLESEX UNIVERSITY HOSPITAL NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RRP') THEN 'BARNET, ENFIELD AND HARINGEY MENTAL HEALTH NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RKE') THEN 'THE WHITTINGTON HOSPITAL NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RNK') THEN 'TAVISTOCK AND PORTMAN NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('R1H') THEN 'BARTS HEALTH NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RF4') THEN 'BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOSPITALS NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RWK') THEN 'EAST LONDON NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RQX') THEN 'HOMERTON UNIVERSITY HOSPITAL NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RAT') THEN 'NORTH EAST LONDON NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RYJ') THEN 'IMPERIAL COLLEGE HEALTHCARE NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RT3') THEN 'ROYAL BROMPTON & HAREFIELD NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RQM') THEN 'CHELSEA AND WESTMINSTER HOSPITAL NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RKL') THEN 'WEST LONDON MENTAL HEALTH NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RV3') THEN 'CENTRAL AND NORTH WEST LONDON NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RAS') THEN 'THE HILLINGDON HOSPITALS NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RYX') THEN 'CENTRAL LONDON COMMUNITY HEALTHCARE NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RJ1') THEN 'GUYS AND ST THOMAS NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RJZ') THEN 'KINGS COLLEGE HOSPITAL NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RV5') THEN 'SOUTH LONDON AND MAUDSLEY NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RJ2') THEN 'LEWISHAM HEALTHCARE NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RPG') THEN 'OXLEAS NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RJ7') THEN 'ST GEORGES HEALTHCARE NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RVR') THEN 'EPSOM AND ST HELIER UNIVERSITY HOSPITALS NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RQY') THEN 'SOUTH WEST LONDON AND ST GEORGES MENTAL HEALTH NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RJ6') THEN 'CROYDON HEALTH SERVICES NHS TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RAX') THEN 'KINGSTON HOSPITAL NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('RPY') THEN 'THE ROYAL MARSDEN NHS FOUNDATION TRUST'
  WHEN [PROVIDER_CODE_DERIVED] in ('R1K') THEN 'LONDON NORTH WEST UNIVERSITY HEALTHCARE NHS TRUST'
  ELSE 'Other'  		
  END AS Provider_derived
  
  FROM [ECDS].[dbo].[vtECDS]
  LEFT JOIN [ECDS].[dbo].[vtECDS_INVESTIGATION]
  ON [ECDS].[dbo].[vtECDS].[PheKey] = [ECDS].[dbo].[vtECDS_INVESTIGATION].[PheKey] AND [ECDS].[dbo].[vtECDS].[FYEAR] = [ECDS].[dbo].[vtECDS_INVESTIGATION].[FYEAR]
  WHERE [PROVIDER_CODE_DERIVED] in ('RRV','RP4','RAL','RAN','RAP','RRP','RP6','RKE','RNK','R1H','RF4','RWK','RQX','RAT', 'RYJ','RT3','RQM','RKL','R1K','RV3','RAS','RYX'
  , 'RJ1','RJZ','RV5','RJ2','RPG', 'RJ7','RVR','RQY','RJ6','RAX','RPY') -- include down by only London
  and [AGE_AT_ARRIVAL] > 15
  AND [ECDS].[dbo].[vtECDS].[FYEAR] = '2223'
  and [ECDS].[dbo].[vtECDS].[ARRIVAL_MONTH] between 3 and 12
  and [PROVIDER_CODE_DERIVED] in ('R1H','RWK','RQX','RAT', 'R0A')"
)


#Query to get PII for linkage
ECDS_PII <- DBI::dbGetQuery(conn = Y006, statement = "SELECT
[FYEAR]
,[rowid]
,[NHS_NUMBER]
FROM dbo.vECDS_PID
WHERE FYEAR = '2223' "
                            )


#Join PII onto ECDS table
ECDS_JOIN_PII <- left_join(ECDS_2223_main, ECDS_PII, by=c("FYEAR" = "FYEAR",
                                                     "PheKey" = "rowid"))


#Create table of HIV tests carried out in A+E in London from March
HIV_TESTS <- DBI::dbGetQuery(conn = Sentinel , statement = "
SELECT [PATID]
,[DUPE_SAMPLE]
,[DATETEST]
,MONTH([DATETEST]) TESTMONTH
,YEAR([DATETEST]) year
,[SEX]
,[AGE]
,[NHS_NUMBER]
,[AGE_GROUP]
,[SUM_ETHNICITY]
,[SPECIALITY]
,[SPECGROUP]
,[PHLS]
,[PCT_NAME]
,[CCG]
,[SAMPLE_TYPE]
,[INCLUDE]
,[Exclude]
,[Age1]
,[Ethnicity]

FROM [NIS_HepatitisSentinel].[dbo].[HIVTESTS]
WHERE DATETEST > '2022-02-28' AND PHEC = 'LONDON' AND SPECIALITY = 'CASUALAE'"
)


                                    

#Create table of HIV tests carried out in A+E in London from March
HIV_FINAL <- DBI::dbGetQuery(conn = Sentinel , statement = "
SELECT
[DUPE_SAMPLE]
,[DATETEST]
,MONTH([DATETEST]) TESTMONTH
,[Result2]

FROM [NIS_HepatitisSentinel].[dbo].[HIV_Final]
WHERE DATETEST > '2022-02-28' AND PHEC = 'LONDON' AND SPEC1 = 'CASUALAE'"
)




HCV_tests <- DBI::dbGetQuery(conn = Sentinel , statement = "SELECT
a.[PATID]
,a.[DUPE_SAMPLE]
,b.NHS_NUMBER
,a.[DATETEST]
,MONTH([DATETEST]) TESTMONTH
,a.[HCV]
,a.[RECORD_LOCATION]
,a.[PHLS]
,a.[INCLUDE]
,a.[SEX]
,a.[AGE_GROUP]
,a.[ETHNICITY]
,a.[ONOSUB]
,a.[ONOAREA]
,a.[SAMPLETYPE]
,a.[SPECIALITY]
,a.[PCT_NAME]
,a.[PHEC]
,a.[ODN]
,a.[Exclude]
,[Age1]
,a.[Agegroup1]
FROM [NIS_HepatitisSentinel].[dbo].[HCVTESTS] as a
LEFT JOIN [NIS_HepatitisSentinel].[dbo].[PATIENTIDENTIFIERS_Nov2022] as b
ON a.PATID = b.PATIENT_ID
 WHERE DATETEST > '2022-02-28' AND SPECGROUP = 'CASUALAE' "                           
)












#Case statements for use when needed

,CASE 			
WHEN [PROVIDER_CODE_DERIVED] in ('RRV','RP4','RAL','RAN','RAP','RRP','RP6','RKE','RNK') THEN 'NCL'		
WHEN [PROVIDER_CODE_DERIVED] in ('R1H','RF4','RWK','RQX','RAT')   THEN 'NEL'		
WHEN [PROVIDER_CODE_DERIVED] in ('RYJ','RT3','RQM','RKL','R1K','RV3','RAS','RYX') THEN 'NWL'		
WHEN [PROVIDER_CODE_DERIVED] in ('RJ1','RJZ','RV5','RJ2','RPG')   THEN 'SEL'		
WHEN [PROVIDER_CODE_DERIVED] in ('RJ7','RVR','RQY','RJ6','RAX','RPY')   THEN 'SWL'		
ELSE 'Other'  		
END AS London_Provider_ICS

, CASE 
WHEN [PROVIDER_CODE_DERIVED] in ('RRV') THEN 'UNIVERSITY COLLEGE LONDON HOSPITALS NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RP4') THEN 'GREAT ORMOND STREET HOSPITAL FOR CHILDREN NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RAL') THEN 'ROYAL FREE LONDON NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RP6') THEN 'MOORFIELDS EYE HOSPITAL NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RAN') THEN 'ROYAL NATIONAL ORTHOPAEDIC HOSPITAL NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RAP') THEN 'NORTH MIDDLESEX UNIVERSITY HOSPITAL NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RRP') THEN 'BARNET, ENFIELD AND HARINGEY MENTAL HEALTH NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RKE') THEN 'THE WHITTINGTON HOSPITAL NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RNK') THEN 'TAVISTOCK AND PORTMAN NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('R1H') THEN 'BARTS HEALTH NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RF4') THEN 'BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOSPITALS NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RWK') THEN 'EAST LONDON NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RQX') THEN 'HOMERTON UNIVERSITY HOSPITAL NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RAT') THEN 'NORTH EAST LONDON NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RYJ') THEN 'IMPERIAL COLLEGE HEALTHCARE NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RT3') THEN 'ROYAL BROMPTON & HAREFIELD NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RQM') THEN 'CHELSEA AND WESTMINSTER HOSPITAL NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RKL') THEN 'WEST LONDON MENTAL HEALTH NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RV3') THEN 'CENTRAL AND NORTH WEST LONDON NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RAS') THEN 'THE HILLINGDON HOSPITALS NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RYX') THEN 'CENTRAL LONDON COMMUNITY HEALTHCARE NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RJ1') THEN 'GUYS AND ST THOMAS NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RJZ') THEN 'KINGS COLLEGE HOSPITAL NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RV5') THEN 'SOUTH LONDON AND MAUDSLEY NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RJ2') THEN 'LEWISHAM HEALTHCARE NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RPG') THEN 'OXLEAS NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RJ7') THEN 'ST GEORGES HEALTHCARE NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RVR') THEN 'EPSOM AND ST HELIER UNIVERSITY HOSPITALS NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RQY') THEN 'SOUTH WEST LONDON AND ST GEORGES MENTAL HEALTH NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RJ6') THEN 'CROYDON HEALTH SERVICES NHS TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RAX') THEN 'KINGSTON HOSPITAL NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('RPY') THEN 'THE ROYAL MARSDEN NHS FOUNDATION TRUST'
WHEN [PROVIDER_CODE_DERIVED] in ('R1K') THEN 'LONDON NORTH WEST UNIVERSITY HEALTHCARE NHS TRUST'
ELSE 'Other'  		
END AS London_Provider 
  
 ,CASE 
   WHEN Age_At_Arrival between 16 and 25 THEN '16-25'
   WHEN Age_At_Arrival between 26 and 35 THEN '26-35'
   WHEN Age_At_Arrival between 36 and 45 THEN '36-45'
   WHEN Age_At_Arrival between 46 and 55 THEN '46-55'
   WHEN Age_At_Arrival between 56 and 65 THEN '56-65'
   WHEN Age_At_Arrival > 65 THEN 'Over 65'
  END as 'Age_Range_10yr'






  
  
  
